version: '3.7'

services:
  crypto-alert:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
    container_name: crypto-alert
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: yarn start